-- Script for warm up task, counting the co-occurences of entities

-- @param dir  the directory where the occs.tsv stores (generated by ExtractOccsFromWikipedia)
-- @author hector.liu

occs = LOAD '$dir/occs.tsv' USING PigStorage('\t') AS (id,uri,surfaceForm,context,offset);
docEntPair = FOREACH occs GENERATE STRSPLIT(id,'-',2), uri;
dump docEntPair
